// Code generated by hertz generator.

package question

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _questionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _genquestionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getquestionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkanswerMw() []app.HandlerFunc {
	// your code...
	return nil
}
